# Setting up our modules

In [1]:
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [4]:
session_heatmap = Table.read_table('Session_HeatMap.csv')
session_heatmap.show()

# Row Operations

In [5]:
eight_am = session_heatmap.row(1) 
eight_am

Row(Sign-In Hour=8, Monday=10, Tuesday=29, Wednesday=30, Thursday=24, Friday=22)

In [6]:
eight_am.item(1)

10

In [7]:
eight_am.item('Monday')

10

In [8]:
sum(eight_am)

123

In [9]:
sum(eight_am) - eight_am.item(0)

115

In [10]:
sum(eight_am) - eight_am.item('Sign-In Hour')

115

In [15]:
session_heatmap.apply(np.average)# - session_heatmap.column('Sign-In Hour')

array([  7,  30,  85,  96,  90, 165,  86,  75,  64,  51,  72,  29,  19,  20])

In [17]:
session_heatmap.with_column('Max Sign-In', (session_heatmap.apply(np.average)))

Sign-In Hour | Monday | Tuesday | Wednesday | Thursday | Friday | Max Sign-In
7            | 0      | 2       | 2         | 4        | 2      | 2.83333
8            | 10     | 29      | 30        | 24       | 22     | 20.5
9            | 41     | 41      | 85        | 44       | 47     | 44.5
10           | 60     | 61      | 96        | 57       | 55     | 56.5
11           | 63     | 78      | 90        | 69       | 45     | 59.3333
12           | 92     | 99      | 165       | 140      | 77     | 97.5
13           | 76     | 86      | 67        | 85       | 63     | 65
14           | 53     | 68      | 42        | 75       | 35     | 47.8333
15           | 64     | 34      | 53        | 35       | 15     | 36
16           | 43     | 51      | 49        | 25       | 3      | 31.1667
... (4 rows omitted)

# Probability Simulations 

In [18]:
coin = make_array('heads','tails')
coin

array(['heads', 'tails'],
      dtype='<U5')

In [20]:
dice = np.arange(6)+1
dice

array([1, 2, 3, 4, 5, 6])

In [37]:
dice_outcomes = make_array()

for first_die in dice:
    trial = make_array(first_die)
    
    for second_die in dice:
        trial = np.append(trial,second_die)
        
        for third_die in dice:
            trial =  np.append(trial,third_die)
            
            for fourth_die in dice:
                trial = np.append(trial,fourth_die)
                
                dice_outcomes = np.append(dice_outcomes,trial)

dice_outcomes.item(0)
#this got way out of hand, will fix this for Thursday

1.0

In [36]:
170424/1296

131.5

In [41]:
outcomes = 0
dice_rolls = 0
#the for-loops below simulate the rolling of my 4 dice.
for first_die in dice: 
    for second_die in dice:
        for third_die in dice:
            for fourth_die in dice:
                
                #the array created below stores my outcomes for the four dice. 
                sample_outcome = make_array(first_die,second_die,third_die,fourth_die)
                
                #since I rolled my 4 dice increase the count of dice rolls by one
                dice_rolls += 1 # is the same as: (dice_rolls = dice_rolls + 1) i.e. increases the count by 1
                
                #check to see if there is at least one '6'
                if np.count_nonzero(sample_outcome == 6) >= 1: #True if there is at least one '6' in the sample outcome array
                    outcomes += 1
                
                print(sample_outcome)
print(outcomes)
print(dice_rolls)

[1 1 1 1]
[1 1 1 2]
[1 1 1 3]
[1 1 1 4]
[1 1 1 5]
[1 1 1 6]
[1 1 2 1]
[1 1 2 2]
[1 1 2 3]
[1 1 2 4]
[1 1 2 5]
[1 1 2 6]
[1 1 3 1]
[1 1 3 2]
[1 1 3 3]
[1 1 3 4]
[1 1 3 5]
[1 1 3 6]
[1 1 4 1]
[1 1 4 2]
[1 1 4 3]
[1 1 4 4]
[1 1 4 5]
[1 1 4 6]
[1 1 5 1]
[1 1 5 2]
[1 1 5 3]
[1 1 5 4]
[1 1 5 5]
[1 1 5 6]
[1 1 6 1]
[1 1 6 2]
[1 1 6 3]
[1 1 6 4]
[1 1 6 5]
[1 1 6 6]
[1 2 1 1]
[1 2 1 2]
[1 2 1 3]
[1 2 1 4]
[1 2 1 5]
[1 2 1 6]
[1 2 2 1]
[1 2 2 2]
[1 2 2 3]
[1 2 2 4]
[1 2 2 5]
[1 2 2 6]
[1 2 3 1]
[1 2 3 2]
[1 2 3 3]
[1 2 3 4]
[1 2 3 5]
[1 2 3 6]
[1 2 4 1]
[1 2 4 2]
[1 2 4 3]
[1 2 4 4]
[1 2 4 5]
[1 2 4 6]
[1 2 5 1]
[1 2 5 2]
[1 2 5 3]
[1 2 5 4]
[1 2 5 5]
[1 2 5 6]
[1 2 6 1]
[1 2 6 2]
[1 2 6 3]
[1 2 6 4]
[1 2 6 5]
[1 2 6 6]
[1 3 1 1]
[1 3 1 2]
[1 3 1 3]
[1 3 1 4]
[1 3 1 5]
[1 3 1 6]
[1 3 2 1]
[1 3 2 2]
[1 3 2 3]
[1 3 2 4]
[1 3 2 5]
[1 3 2 6]
[1 3 3 1]
[1 3 3 2]
[1 3 3 3]
[1 3 3 4]
[1 3 3 5]
[1 3 3 6]
[1 3 4 1]
[1 3 4 2]
[1 3 4 3]
[1 3 4 4]
[1 3 4 5]
[1 3 4 6]
[1 3 5 1]
[1 3 5 2]
[1 3 5 3]
[1 3 5 4]


In [40]:
671/1296

0.5177469135802469

In [42]:
dice

array([1, 2, 3, 4, 5, 6])

In [43]:
(5/6)**4

0.4822530864197532

In [44]:
1 - (5/6)**4

0.5177469135802468