# Setting up our modules

In [1]:
import numpy as np
from datascience import *

In [2]:
spotify = Table.read_table('Spotify_final_dataset.csv')

In [3]:
spotify

Position | Artist Name   | Song Name                                  | Days | Top 10 (xTimes) | Peak Position | Peak Position (xTimes) | Peak Streams | Total Streams
1        | Post Malone   | Sunflower  SpiderMan: Into the SpiderVerse | 1506 | 302             | 1             | (x29)                  | 2118242      | 883369738
2        | Juice WRLD    | Lucid Dreams                               | 1673 | 178             | 1             | (x20)                  | 2127668      | 864832399
3        | Lil Uzi Vert  | XO TOUR Llif3                              | 1853 | 212             | 1             | (x4)                   | 1660502      | 781153024
4        | J. Cole       | No Role Modelz                             | 2547 | 6               | 7             | 0                      | 659366       | 734857487
5        | Post Malone   | rockstar                                   | 1223 | 186             | 1             | (x124)                 | 2905678      | 718865961
6        | Travis Scott  | goosebumps                                 | 1995 | 4               | 8             | 0                      | 977275       | 672972704
7        | The Weeknd    | Blinding Lights                            | 1100 | 233             | 1             | (x11)                  | 2355059      | 644287953
8        | XXXTENTACION  | Jocelyn Flores                             | 1673 | 44              | 2             | (x1)                   | 3175206      | 624457164
9        | XXXTENTACION  | SAD!                                       | 1217 | 133             | 1             | (x6)                   | 4437612      | 619879245
10       | Juice WRLD    | All Girls Are The Same                     | 1681 | 2               | 5             | 0                      | 1239152      | 613872384
... (11074 rows omitted)

About 'spotify' 

One of the biggest music streaming platform, but who's the biggest streamed here? This dataset which is webscrapped and accumulated all the stream metrics of each artist and their respective songs.<br>

Position - Spotify Ranking <br>
Artist Name - Artist Name <br>
Song Name - Song Name <br>
Days - No of days since the release of the song (Updated) <br>
Top 10 (xTimes) - No of times inside top 10 <br>
Peak Position - Peak position attained <br>
Peak Position (xTimes) - No of times Peak position attained <br>
Peak Streams - Total no of streams during Peak position <br>
**Total Streams **- Total song streams

# Comparison Expressions and Operations

In [4]:
2>3

False

In [5]:
x = 4
x >= 3

True

In [6]:
y = 7
x <= y

True

In [7]:
x == y

False

In [8]:
c = x*3
c == 6

False

In [9]:
x != 3

True

In [11]:
print(x,c,y)

4 12 7


In [12]:
x < y < c

True

# Aggregating Comparisons

In [14]:
this = make_array(1,2,3,4,5,6,7,8)
sum(this >= 5) #this gives me the number of values that are larger than, or equal to, the number 5 

4

In [16]:
drinks = make_array('Coffee','Latte','Mocha','Coffee','Frappacino')

In [17]:
drinks == 'Coffee'

array([ True, False, False,  True, False], dtype=bool)

In [18]:
sum(drinks == 'Coffee')

2

In [21]:
np.count_nonzero(drinks == 'Coffee')

2

## Practice question: 

In [22]:
spotify

Position | Artist Name   | Song Name                                  | Days | Top 10 (xTimes) | Peak Position | Peak Position (xTimes) | Peak Streams | Total Streams
1        | Post Malone   | Sunflower  SpiderMan: Into the SpiderVerse | 1506 | 302             | 1             | (x29)                  | 2118242      | 883369738
2        | Juice WRLD    | Lucid Dreams                               | 1673 | 178             | 1             | (x20)                  | 2127668      | 864832399
3        | Lil Uzi Vert  | XO TOUR Llif3                              | 1853 | 212             | 1             | (x4)                   | 1660502      | 781153024
4        | J. Cole       | No Role Modelz                             | 2547 | 6               | 7             | 0                      | 659366       | 734857487
5        | Post Malone   | rockstar                                   | 1223 | 186             | 1             | (x124)                 | 2905678      | 718865961
6        | Travis Scott  | goosebumps                                 | 1995 | 4               | 8             | 0                      | 977275       | 672972704
7        | The Weeknd    | Blinding Lights                            | 1100 | 233             | 1             | (x11)                  | 2355059      | 644287953
8        | XXXTENTACION  | Jocelyn Flores                             | 1673 | 44              | 2             | (x1)                   | 3175206      | 624457164
9        | XXXTENTACION  | SAD!                                       | 1217 | 133             | 1             | (x6)                   | 4437612      | 619879245
10       | Juice WRLD    | All Girls Are The Same                     | 1681 | 2               | 5             | 0                      | 1239152      | 613872384
... (11074 rows omitted)

#### In the cell above, we saved a data table of Spotify Top 10000 streamed songs. Let's load the cell below with an array containing the peak position of each song.

In [24]:
spotify_peak = spotify.column('Peak Position')

In [25]:
spotify_peak

array([  1,   1,   1, ..., 167, 200, 184])

#### Let's construct an array that tells us whether each song reached the #1 peak position.

In [29]:
did_it_peak = (spotify_peak == 1) #spotify_peak==1 is creating an array that tells me whether the song peaked at #1
did_it_peak #, then stored it in the variable I call: 'did_it_peak'

array([ True,  True,  True, ..., False, False, False], dtype=bool)

#### Now use the sum function to determine the number of songs in this dataset which peaked at #1. 

In [30]:
sum(did_it_peak)

190

In [31]:
np.count_nonzero(did_it_peak)

190

#### This line of thinking is *very similar* to a method we have gotten quite familiar with recently. Use that method to verify our solution we just found.

In [35]:
len(spotify.where('Peak Position',are.equal_to(1)).column('Peak Position'))

190

In [33]:
spotify.where('Peak Position',are.equal_to(1)).num_rows

190

# Control Statements 'If'

In [37]:
x = 20
s = 'You are 20'
s

'You are 20'

In [38]:
if x >= 18:
    s = 'You can legally vote'
s

'You can legally vote'

In [39]:
if x >= 21: 
    s = 'You may enter this bar/nightclub'
s 

'You can legally vote'

In [40]:
x = 25 

In [41]:
if x >= 21: 
    s = 'You may enter this bar/nightclub'
s 

'You may enter this bar/nightclub'

In [43]:
def age(input_age):
    if input_age >= 18:
        return 'You can legally vote'
    if input_age >= 21:
        return 'You can legally drink'

In [48]:
age(3)

'You can legally drink milk'

In [49]:
age(20)

'You can legally vote'

In [50]:
age(25)

'You can legally drink'

awkward.... Let's fix the age function below:

In [47]:
def age(input_age):
    if input_age >= 21:
        return 'You can legally drink'
    elif input_age >= 18: #this only gets checked if the 'if' condition above is false
        return 'You can legally vote'
    else: #only runs if all the if/elif conditions above were false
        return 'You can legally drink milk'

# Control Statements 'for' a.k.a. the 'for'-loop

In [51]:
for pet in make_array('cat','dog','rabbit','ferret'):
    print('I love my '+ pet)

I love my cat
I love my dog
I love my rabbit
I love my ferret


In [52]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [53]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


#### Exercise:

Let's use a for-loop to code for a song that is **extremely** repetitive: "99 bottles of Beer"...

In [54]:
np.arange(99,0,-1)

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [56]:
for i in np.arange(99,0,-1):
    print(i,'bottles of beer on the wall' )
    print(i, 'bottles of beer')
    print('take one down, pass it around')
    print(i-1,'bottles of beer on the wall')
i

99 bottles of beer on the wall
99 bottles of beer
take one down, pass it around
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
take one down, pass it around
97 bottles of beer on the wall
97 bottles of beer on the wall
97 bottles of beer
take one down, pass it around
96 bottles of beer on the wall
96 bottles of beer on the wall
96 bottles of beer
take one down, pass it around
95 bottles of beer on the wall
95 bottles of beer on the wall
95 bottles of beer
take one down, pass it around
94 bottles of beer on the wall
94 bottles of beer on the wall
94 bottles of beer
take one down, pass it around
93 bottles of beer on the wall
93 bottles of beer on the wall
93 bottles of beer
take one down, pass it around
92 bottles of beer on the wall
92 bottles of beer on the wall
92 bottles of beer
take one down, pass it around
91 bottles of beer on the wall
91 bottles of beer on the wall
91 bottles of beer
take one down, pass it around
90 bottles of beer on the wall
9

1

1

#### Exercise:

Consider the following string:

In [58]:
STEM_Center_Webpage_string = 'The Skyline College STEM Center brings together academic and student support services for students taking science, technology, engineering and math courses.The center supports student success by ensuring students have access to resources such as academic tutoring, counseling services, a resource depository for STEM pathways and transfer, a hub for internships and work based learning opportunities, as well as a place where students and staff can collaborate and build a community and supportive connection. This STEM Center was brought to campus by a U.S. Department of Education, Title V, Developing Hispanic-Serving Institutions Program “Strengthening Pathways to Success in STEM” grant awarded in 2018.'
STEM_Center_Webpage_string

'The Skyline College STEM Center brings together academic and student support services for students taking science, technology, engineering and math courses.The center supports student success by ensuring students have access to resources such as academic tutoring, counseling services, a resource depository for STEM pathways and transfer, a hub for internships and work based learning opportunities, as well as a place where students and staff can collaborate and build a community and supportive connection. This STEM Center was brought to campus by a U.S. Department of Education, Title V, Developing Hispanic-Serving Institutions Program “Strengthening Pathways to Success in STEM” grant awarded in 2018.'

We'll use the .split() method to store each word into a list:

In [61]:
STEM_split = STEM_Center_Webpage_string.split()
#STEM_split

Now, use a for-loop to check the list to see how many times 'student' is mentioned on the webpage

In [70]:
count_when_student_is_mentioned = 0
for word in STEM_split:
    if word == 'student':
        #print('FOUND IT')
        count_when_student_is_mentioned = count_when_student_is_mentioned + 1
    elif word == 'students':
        #print('FOUND PLURAL')
        count_when_student_is_mentioned += 1
    #print('checked:',word)
    
count_when_student_is_mentioned

5